import pandas

# Global parameters (same for all samples)
GLOBAL_PARAMS = {
    ### scVI annotation merge
    "merge_annotations_scvi_annotation_df_path": "xenium_directannotation_resolvi_v1-withadult.csv",
    "merge_annotations_scvi_merge_cols": [
        "cell_id",
        "leiden",
        "broad_annotation",
        "fine_annotation",
        "lineage",
        "batch",
    ],
    "merge_annotations_scvi_on_col": ["cell_id", "batch"],
    ### DOT annotation merge
    "merge_annotations_DOT_annotation_df_path": "xenium_indirectannotation_DOT_plotting_fixed.csv",
    "merge_annotations_DOT_merge_cols": [
        "cell_id",
        "batch",
        "coarse_annotation_predictedDOT",
    ],
    "merge_annotations_DOT_on_col": ["cell_id", "batch"],
    ### Stromal spatial_axis (single)
    "spatial_axis_stromal_single_annotation_column": "fine_annotation",
    "spatial_axis_stromal_single_k_neighbours": 15,
    "spatial_axis_stromal_single_annotation_order": ["Stroma_OutCor"],
    "spatial_axis_stromal_single_save_column": "stromal_single_spatial_axis",
    ### Stromal spatial_axis (multiple)
    "spatial_axis_stromal_multiple_annotation_column": "fine_annotation",
    "spatial_axis_stromal_multiple_k_neighbours": 15,
    "spatial_axis_stromal_multiple_annotation_order": [
        "Stroma_OutCor_OSE",
        "Stroma_OutCor",
        "Stroma_OutCor_Foll",
        "Stroma_InnCor",
        "Stroma_Medulla",
    ],
    "spatial_axis_stromal_multiple_save_column": "stromal_multiple_spatial_axis",
    ### Growing spatial_axis
    "spatial_axis_growing_annotation_column": "fine_annotation",
    "spatial_axis_growing_k_neighbours": 15,
    "spatial_axis_growing_annotation_order": ["Theca_1perifollicular_cycling"],
    "spatial_axis_growing_save_column": "growing_follicle_spatial_axis",
    "spatial_axis_growing_distance_threshold": 25,
    "spatial_axis_growing_distance_k_neighbors": 5,
    "spatial_axis_growing_scaling_factor": 1,  # Scaling factor isn't required for knn > 1 since we compute relative distances
    "spatial_axis_growing_normalise": "true",
    ### Atretic spatial_axis
    "spatial_axis_atretic_annotation_column": "coarse_annotation_predictedDOT",
    "spatial_axis_atretic_k_neighbours": 15,
    "spatial_axis_atretic_annotation_order": ["Theca_Atr"],
    "spatial_axis_atretic_save_column": "atretic_follicle_spatial_axis",
    "spatial_axis_atretic_distance_threshold": 25,
    "spatial_axis_atretic_distance_k_neighbors": 5,
    "spatial_axis_atretic_scaling_factor": 1,  # Scaling factor isn't required for knn > 1 since we compute relative distances
    "spatial_axis_atretic_normalise": "true",
    ### Growing spatial_axis (KNN=1)
    "spatial_axis_growing_k_neighbours_knn1": 1,
    "spatial_axis_growing_knn1_save_column": "growing_follicle_spatial_axis_knn_1",
    "spatial_axis_growing_knn1_distance_threshold": 25,  # In microns
    "spatial_axis_growing_knn1_distance_k_neighbors": 5,
    "spatial_axis_growing_knn1_scaling_factor": 0.2125,
    "spatial_axis_growing_knn1_normalise": False,
    ### Atretic spatial_axis (KNN=1)
    "spatial_axis_atretic_k_neighbours_knn1": 1,
    "spatial_axis_atretic_knn1_save_column": "atretic_follicle_spatial_axis_knn_1",
    "spatial_axis_atretic_knn1_distance_threshold": 25,  # In microns
    "spatial_axis_atretic_knn1_distance_k_neighbors": 5,
    "spatial_axis_atretic_knn1_scaling_factor": 0.2125,
    "spatial_axis_atretic_knn1_normalise": False,
}

samples = [
    {
        "sample_id": "AU20_S45",
        "path": "AU20/AU20_S45.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU20_S29",
        "path": "AU20/AU20_S29.zarr",
        "run_stromal": False,
        "run_growing": True,
        "run_atretic": False,
        "original_shapes_key": "target_image_shapes_AU20_S29_spatial_morphology",
        "new_shapes_key": "AU20_S29_histology",
    },
    {
        "sample_id": "AU20_S10",
        "path": "AU20/AU20_S10_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": "target_image_shapes_AU20_S10_spatial_morphology",
        "new_shapes_key": "AU20_S10_histology",
    },
    {
        "sample_id": "AU20_S40",
        "path": "AU20/AU20_S40.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": "target_image_shapes_AU20_S40_spatial_morphology",
        "new_shapes_key": "AU20_S40_histology",
    },
    {
        "sample_id": "AU20_S34",
        "path": "AU20/AU20_S34_adjacent.zarr",
        "run_stromal": True,
        "run_growing": True,
        "run_atretic": False,
        "original_shapes_key": "target_image_shapes_AU20_S34_spatial_morphology",
        "new_shapes_key": "AU20_S34_histology",
    },
    {
        "sample_id": "AU20_S25",
        "path": "AU20/AU20_S25_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": "target_image_shapes_AU20_S25_spatial_morphology",
        "new_shapes_key": "AU20_S25_histology",
    },
    {
        "sample_id": "AU14_S44",
        "path": "AU14/AU14_S44_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU14_S49",
        "path": "AU14/AU14_S49_adjacent.zarr",
        "run_stromal": True,
        "run_growing": True,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU14_S38",
        "path": "AU14/AU14_S38_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU14_S14",
        "path": "AU14/AU14_S14.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU14_S33",
        "path": "AU14/AU14_S33.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU14_S29",
        "path": "AU14/AU14_S29.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": True,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU16_S36",
        "path": "AU16/AU16_S36.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU16_S39",
        "path": "AU16/AU16_S39.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU16_S10",
        "path": "AU16/AU16_S10.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU16_S43",
        "path": "AU16/AU16_S43.zarr",
        "run_stromal": True,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": "target_image_shapes_AU16_S43_spatial_morphology",
        "new_shapes_key": "AU16_S43_histology",
    },
    {
        "sample_id": "AU16_S6",
        "path": "AU16/AU16_S6_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU16_S15",
        "path": "AU16/AU16_S15.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU16_S21",
        "path": "AU16/AU16_S21.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU30_S43",
        "path": "AU30/AU30_S43_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU30_S28",
        "path": "AU30/AU30_S28.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU30_S16",
        "path": "AU30/AU30_S16.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": "target_image_shapes_AU30_S16_spatial_morphology",
        "new_shapes_key": "AU30_S16_histology",
    },
    {
        "sample_id": "AU30_S22",
        "path": "AU30/AU30_S22_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU30_S48",
        "path": "AU30/AU30_S48_adjacent.zarr",
        "run_stromal": True,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": "target_image_shapes_AU30_S48_spatial_morphology",
        "new_shapes_key": "AU30_S48_histology",
    },
    {
        "sample_id": "AU30_S12",
        "path": "AU30/AU30_S12_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU18_S19",
        "path": "AU18/AU18_S19.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": "target_image_shapes_AU18_S19_spatial_morphology",
        "new_shapes_key": "AU18_S19_histology",
    },
    {
        "sample_id": "AU18_S45",
        "path": "AU18/AU18_S45_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU18_S10",
        "path": "AU18/AU18_S10_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU18_S25",
        "path": "AU18/AU18_S25_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU18_S13",
        "path": "AU18/AU18_S13_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU18_S40",
        "path": "AU18/AU18_S40_adjacent.zarr",
        "run_stromal": True,
        "run_growing": False,
        "run_atretic": True,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU15_S6",
        "path": "AU15/AU15_S6.zarr",
        "run_stromal": True,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU15_S26",
        "path": "AU15/AU15_S26_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU15_S37",
        "path": "AU15/AU15_S37_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU15_S31",
        "path": "AU15/AU15_S31_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU15_S22",
        "path": "AU15/AU15_S22_adjacent.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU15_S42",
        "path": "AU15/AU15_S42.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU22_S8",
        "path": "AU22/AU22_S8.zarr",
        "run_stromal": True,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU22_S17",
        "path": "AU22/AU22_S17.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU22_S23",
        "path": "AU22/AU22_S23.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU22_S43",
        "path": "AU22/AU22_S43.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU22_S12",
        "path": "AU22/AU22_S12.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": False,
        "new_shapes_key": False,
    },
    {
        "sample_id": "AU22_S38",
        "path": "AU22/AU22_S38.zarr",
        "run_stromal": False,
        "run_growing": False,
        "run_atretic": False,
        "original_shapes_key": "target_image_shapes_AU22_S38_spatial_morphology",
        "new_shapes_key": "AU22_S38_histology",
    },
]

# Create DataFrame and add global params
df = pandas.DataFrame(samples)

for key, value in GLOBAL_PARAMS.items():
    df[key] = [value] * len(df)

print("\n", df)

df.to_csv(
    "sample_sheet.csv",
    index=False,
    sep="\t",
)
